# Generated by Django 4.0 on 2022-03-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='em_estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='esta_ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
